baseurl = "https://blog.players1.st/"
title = "Players1st ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚ºãƒ•ã‚¡ãƒ¼ã‚¹ãƒˆ Blog"
theme = "showfolio"
languageCode = "ja-jp"

googleAnalytics = "UA-73836462-6"

baseURL = "https://example.com"
languageCode = "en-us"
title = "Anubis"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
name = "Players1st"

[params]
author = "Players1st"
description = "Players1st(ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚ºãƒ•ã‚¡ãƒ¼ã‚¹ãƒˆ)ã¯ã€æœˆé¡ã‚¹ãƒãƒ³ã‚µãƒ¼å‹Ÿé›†ã«ã‚ˆã£ã¦é¸æ‰‹æ´»å‹•ã«å¿…è¦ãªè³‡é‡‘ã‚’ç¶™ç¶šçš„ã«å¾—ã‚‹ã“ã¨ãŒã§ãã¾ã™ã€‚ãƒ•ã‚¡ãƒ³ã¸ã®ã‚¹ãƒãƒ³ã‚µãƒ¼ç‰¹å…¸ã€ã‚¹ãƒãƒ³ã‚µãƒ¼é™å®šã®ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã‚’æä¾›ã™ã‚‹ã“ã¨ã§ã€ç‰¹åˆ¥ãªé–¢ä¿‚ã‚’ç”Ÿã¿å‡ºã—ã‚¢ã‚¹ãƒªãƒ¼ãƒˆã¨ã—ã¦ã®ä¾¡å€¤ã‚’ã•ã‚‰ã«é«˜ã‚ã¾ã™ã€‚"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.social]]
id = "docs"
url = "https://gohugo.io/documentation/"

[[params.social]]
id = "github"
url = "https://github.com/mitrichius/hugo-theme-anubis"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true





[params]
  name = "Players1st(ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚ºãƒ•ã‚¡ãƒ¼ã‚¹ãƒˆ) Blog"
  description = "Players1st(ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚ºãƒ•ã‚¡ãƒ¼ã‚¹ãƒˆ)ã¯ã€æœˆé¡ã‚¹ãƒãƒ³ã‚µãƒ¼å‹Ÿé›†ã«ã‚ˆã£ã¦é¸æ‰‹æ´»å‹•ã«å¿…è¦ãªè³‡é‡‘ã‚’ç¶™ç¶šçš„ã«å¾—ã‚‹ã“ã¨ãŒã§ãã¾ã™ã€‚ãƒ•ã‚¡ãƒ³ã¸ã®ã‚¹ãƒãƒ³ã‚µãƒ¼ç‰¹å…¸ã€ã‚¹ãƒãƒ³ã‚µãƒ¼é™å®šã®ã‚³ãƒ³ãƒ†ãƒ³ãƒ„ã‚’æä¾›ã™ã‚‹ã“ã¨ã§ã€ç‰¹åˆ¥ãªé–¢ä¿‚ã‚’ç”Ÿã¿å‡ºã—ã‚¢ã‚¹ãƒªãƒ¼ãƒˆã¨ã—ã¦ã®ä¾¡å€¤ã‚’ã•ã‚‰ã«é«˜ã‚ã¾ã™ã€‚"
  author = "Players1st"
  authorEmail = "support@players1.st"
  authorImage = "/photo.png"
  autoDarkMode = true

  copyright = "Copyright &copy; [Players1st](https://company.players1.st)"
  favicon = "favicon.icon"

  [params.homepage]
    title = "Hey ğŸ‘‹ I'm John Doe"
    tagline = "UX Designer and Product Lead"
    description = "Develop functional user interfaces and provide a valuable experience to customers."
    contact = "https://twitter.com/"

  [params.homepage.codepen]
    username = "apvarun"
    pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

  [params.homepage.resume]
    skills = ["Visual Design", "Product Development"]

  [[params.homepage.resume.work]]
    name = "Google"
    role = "Product Engineer"
    duration = "Nov 2019 - Apr 2021"

  [[params.homepage.resume.work]]
    name = "Amazon"
    role = "Sr. UX Designer"
    duration = "Jan 2016 - Oct 2019"

  [[params.homepage.resume.courses]]
    name = "Design Principles"
    provider = "UX Academy"
    duration = "Nov 2019 - Jan 2020"

  [params.homepage.social]
    twitter = "https://twitter.com/"
    linkedin = "https://linkedin.com/in/"
    github = "https://github.com/"
    medium = "https://medium.com/"
    reddit = "https://reddit.com/"
    dribbble = "https://dribbble.com/"

  [build]
    writeStats = true

  # syntax highlight settings
  [markup]
    [markup.highlight]
      style = "dracula"




#   header_image = ""
#   keyword = "players1st, ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚ºãƒ•ã‚¡ãƒ¼ã‚¹ãƒˆ, ã‚¢ã‚¹ãƒªãƒ¼ãƒˆ, é¸æ‰‹, , ã‚¹ãƒãƒ¼ãƒ„, ã‚¹ãƒãƒ³ã‚µãƒ¼å‹Ÿé›†, ãƒ•ã‚¡ãƒ³ãƒ‡ã‚£ãƒ³ã‚°, å€‹äººã‚¹ãƒãƒ³ã‚µãƒ¼, ã‚¹ãƒãƒ³ã‚µãƒ¼, blog"
#   slogan = ""
#
#   image_404 = ""
#   title_404 = "ãƒšãƒ¼ã‚¸ãŒè¦‹ã¤ã‹ã‚Šã¾ã›ã‚“ã§ã—ãŸ :("
#   omit_categories = true
#
#   # leancloud storage for page view counter
#   page_view_conter = false
#   leancloud_app_id = ""
#   leancloud_app_key = ""
#
#   # algolia site search
#   algolia_search = false
#   algolia_appId = ""
#   algolia_indexName = ""
#   algolia_apiKey = ""
#
#   # Sidebar settings
#   sidebar_about_description = "ã‚¢ã‚¹ãƒªãƒ¼ãƒˆãƒ»ã‚¯ãƒ©ãƒ–ãƒãƒ¼ãƒ ã®ãŸã‚ã®æœˆé¡ã‚¹ãƒãƒ³ã‚µãƒ¼å‹Ÿé›†ã‚µã‚¤ãƒˆ é¸æ‰‹æ´»å‹•ã«å¿…è¦ãªè³‡é‡‘ã‚’ç¶™ç¶šçš„ã«å¾—ã‚‹ã“ã¨ãŒã§ãã¾ã™ã€‚"
#   sidebar_avatar = "img/logo-reverse_square.png"      # use absolute URL, seeing it's used in both `/` and `/about/`
#
#   featured_tags = true
#   featured_condition_size = 1
#
#   # Baidu Analytics
#   ba_track_id = ""
#
#   # We need a proxy to access Disqus api in China
#   # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
#   disqus_proxy = ""
#   disqus_site = ""
#
#   # Twikoo comments
#   # Follow https://twikoo.js.org/ to set up your own env_id
#   twikoo_env_id = ""
#
#   #Enable wechat pay & alipay to allow readers send reward money if they like the articles
#   reward = true
#   # reward_guide = "å¦‚æœè¿™ç¯‡æ–‡ç« å¯¹ä½ æœ‰ç”¨,è¯·éšæ„æ‰“èµ"
#
#   friends = true
#   bookmarks = false
#   about_me = true
#
#   # Include any custom CSS and/or JS files, url or relative to /static folder
#   #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
#   #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]
#
#   [params.social]
#   rss            = true
#   twitter        = "https://twitter.com/pys1st"
#   instagram      = "https://www.instagram.com/players1st.web/"
#   facebook       = "https://www.facebook.com/players1st.web"
#   # email          = "support@players1.st"
#   #googleplus    = "full profile url in googleplus"
#   # linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
#   # stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
#   # github         = "https://github.com/yourgithub"
#   # wechat         = "your wechat qr code image"
#   #medium        = "full profile url in medium"
#   #slack         = "full workspace url in slack"
#   #pinterest     = "full profile url in pinterest"
#   #reddit        = "full profile url in reddit"
#   #gitlab        = "full profile url in gitlab"
#   #mastodon      = "full profile url in mastodon"
#   #keybase       = "full profile url in keybase"
#   #xing          = "https://www.xing.com/profile/yourxingid"
#   #git           = "full profile url for git user"
#
#   [[params.friend_link]]
#   title = "Players1st ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã‚ºãƒ•ã‚¡ãƒ¼ã‚¹ãƒˆ"
#   href =  "https://players1.st"
#
#   [[params.friend_link]]
#   title = "é‹å–¶ä¼šç¤¾"
#   href =  "https://company.players1.st"
#
#
# [outputFormats.Algolia]
# baseName = "algolia"
# isPlainText = true
# mediaType = "application/json"
# notAlternative = true
#
# [params.algolia]
# vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
# params = ["categories", "tags"]
#
# [markup]
#   [markup.tableOfContents]
#     endLevel = 2
#     startLevel = 1
#   [markup.highlight]
#     style = "dracula"
